### ISSUE TITLE
Feedback on proposal

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Capital_Bikeshare_Analysis#16]
@Mikeymice and @EvanYathon, you have chosen an interesting data set and you have a good plan. I am curious about the most important predictors for rental bike ridership, so I look forward to the result. Here are some improvement points and minor suggestions for your project.

- Keep in mind that your readme is the landing page for someone examining your analysis. Therefore, you can do some additions that would make the readme more informative and intriguing for a visitor. In particular, you can
	- include a brief introduction about the context and your motivation to do such analysis.
	- explain the data a bit more in detail, state the variables included, or print the head of the data table in the main readme. Including the link to the data source is a good idea, but still explaining the data in your repository is needed.

- I believe you can briefly mention why you chose a decision tree in your analysis. Why do you think this model is suitable for your analysis?

**Minor Suggestions:**
- I would recommend taking "DSCI_522" out of the name of your project. But if you like it this way, no problem.

- Include you Github profile links with your names on the readme.

I hope this feedback is helpful in improving your project. Please let me know if you have any questions. Good luck!

**Comment by Mikeymice** [comment]
Issues addressed

- added github username [commit](https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/0d676f817c43ed25ce57ba1bb74f421541f74362)
- removed "DSCI_522"

**Comment by Mikeymice** [comment]
edited introduction [commit](https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/pull/20/commits/a4a8d1b47309bdc8ffea09f9ff6e9e9dc7acca3d)

**Comment by Mikeymice** [comment]
Updated README with more background info [commit](5bc3e4e994c2022fa8aa0f491d4ac96877771d6c)
