### ISSUE TITLE
Tracking library/package

### ISSUE THREAD

**Issue by Mikeymice** [UBC-MDS/Capital_Bikeshare_Analysis#17]
Think it is a good idea to just have a list of libraries and packages used in our script.

It will make it easy when we start using docker and also help us to run each other's script on our local machine , i assume that you will have to install `pydotplut` and `tqdm`

here is the library used for **summaries_data.py**
```python
# %% load library
import pandas as pd
import numpy as np
import argparse
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn import model_selection
from sklearn.externals.six import StringIO
from sklearn.tree import export_graphviz
import graphviz
from sklearn.model_selection import train_test_split
import pydotplus
from IPython.display import Image
import seaborn as sns
import matplotlib.pyplot as plt
sns.set()
from tqdm import tqdm
```

**load_csv.R**
```r
suppressMessages(library(tidyverse))
suppressMessages(library(lubridate))
library(ggplot2)

```

**Comment by EvanYathon** [comment]
Good idea, here is mine so far for EDA (decided not to use ggpairs as I thought it was complicating the message)

```
suppressMessages(library(tidyverse))
```

**Comment by Mikeymice** [comment]
Moved this dependencies to README.md [0d676f817c43ed25ce57ba1bb74f421541f74362](https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/0d676f817c43ed25ce57ba1bb74f421541f74362)
