### ISSUE TITLE
First draft of report

### ISSUE THREAD

**Issue by EvanYathon** [UBC-MDS/Capital_Bikeshare_Analysis#29]
I've created a first draft of the report, but I think in the analysis section the details about the actual machine learning are a bit light.  Feel free to edit it and include more details or images regarding your findings, or leave suggestions here.  I can take a look at it tomorrow!

**Comment by Mikeymice** [comment]
added accuracy.png and information about the tree [commit](https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/bfa53a7b59cf37f6bd6d1bb43339a5b931be1f05)
