### ISSUE TITLE
To do for Milestone 2

### ISSUE THREAD

**Issue by EvanYathon** [UBC-MDS/Capital_Bikeshare_Analysis#36]
- [x] Comment within `Makefile` for documenting what is happening [commit](https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/b69cb093a097f13253ecb2d28ce1657a62b1981b)
- [x] Document within README.md to explain what it does and how to run it [commit](https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/0ddf0c13fd7bbd46c92ba87de5e45cb09bd56cf5)

**Comment by Mikeymice** [comment]
I can look into this
