### ISSUE TITLE
Feedback on Milestone 2

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Capital_Bikeshare_Analysis#41]
@Mikeymice and @EvanYathon, great job on Milestone 2! All I can add is the following:

- [x] Update the documentation at the beginning of the Makefile. As per Tiffany's instructions on this: "The Makefile must be well documented. This means comments throughout, readable code and a brief summary at the top of each file that answers who wrote it, when it was written and what it does."

**Suggestions:**

- [x] Go through http://swcarpentry.github.io/make-novice/reference. This would help you make your Make code more practical. For example, you can use automatic variables and avoid some repetition. https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/236a74c3ddb28379036ebe1200ad723e44a254bd

**Comment by EvanYathon** [comment]
Mike added documentation to Makefile [this commit](https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/f223efbcc7bbf5146bde709f72f62ed82723ef8c#diff-b67911656ef5d18c4ae36cb6741b7965)

**Comment by Mikeymice** [comment]
updated makefile https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/236a74c3ddb28379036ebe1200ad723e44a254bd
