### ISSUE TITLE
For Final Project:

### ISSUE THREAD

**Issue by EvanYathon** [UBC-MDS/Capital_Bikeshare_Analysis#45]
- [x] Add in code of conduct (Evan)

- [x] Update README with dockerfile instructions and dockerhub repo location (Mike)

- [x] Finish issues from Ozum (Both) https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/236a74c3ddb28379036ebe1200ad723e44a254bd

**Comment by EvanYathon** [comment]
Code of conducted added in this [commit](https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/637dd83e693e784657d1c57ae67dded1bb4a2ece)

**Comment by EvanYathon** [comment]
Mike updated the README with docker instructions in this [commit](https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/f36b6809f50f15cf8502cfb2c144dd9ea4d455b3)

**Comment by Mikeymice** [comment]
updated Makefile to make it more readable
