### ISSUE TITLE
add this citation to your README

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/Capital_Bikeshare_Analysis#47]
https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/blob/43ed6e85193fce3dad2bdabf23b0a79d4bc077a0/data/Readme.txt#L92

I think this citation should be upfront in your project root README.

**Comment by EvanYathon** [comment]
I can take care of this @Mikeymice

**Comment by EvanYathon** [comment]
Issue taken care of [here](https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/dcbd1470e8e3f5d4f5472a3c9cad3c22e166d078).
