### ISSUE TITLE
Fig 4 is very difficult to read

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/Capital_Bikeshare_Analysis#48]
Fig 4 is very difficult to read. Specifically the text in decision tree graphic is far to small to be useful. You could simplify if by rotating it 90 degrees (more room for bigger text!) and including less info on the graphic (value, samples and gini could be in a table in an appendix).

**Comment by Mikeymice** [comment]
changing the figure to different orientation, included sample pic. will make pull request soon 
![dtree](https://user-images.githubusercontent.com/15175882/49689031-c8de8280-facf-11e8-9d98-e5b4e18fe647.png)

**Comment by Mikeymice** [comment]
included to pull request https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/3a9d66526c1d58e4af7ea2bbf9cd630335901156
