### ISSUE TITLE
Fig 3 & 5 are too big

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/Capital_Bikeshare_Analysis#49]
Fig 3 & 5 are too big and take up more room than necessary. The text on the figures is a good size, its just the plot area is unnecessarily big. Its ideal to keep the figure size smallish so that readers can see the whole figure in their browser window at 100% zoom as well as read the figure caption.

**Comment by Mikeymice** [comment]
I will be working on them will soon make pull request . will reduce the size to width 500px for both figures

**Comment by Mikeymice** [comment]
https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/55da8cfb08d0bc632ab9132ea9f95d5b7fdc686e
