### ISSUE TITLE
Test Training Splitting function for future reference

### ISSUE THREAD

**Issue by Mikeymice** [UBC-MDS/Capital_Bikeshare_Analysis#7]
We can also use the function from the `sklearn` library 

`train_test_split` will take X and y and return 4 lists, one pair for training and another pair for testing 

> X_train, X_test, y_train, y_test = train_test_split(X, y)

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

**Comment by EvanYathon** [comment]
Looks like exactly what we need!

**Comment by Mikeymice** [comment]
Used cross validation instead
